// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using userApi.DbContext;

#nullable disable

namespace userApi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("userApi.Entities.ClaimEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Claims");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "For Admin",
                            Name = "Admin Role"
                        },
                        new
                        {
                            Id = 2,
                            Description = "For Editor",
                            Name = "Editor Role"
                        },
                        new
                        {
                            Id = 3,
                            Description = "For User",
                            Name = "User Role"
                        });
                });

            modelBuilder.Entity("userApi.Entities.UserClaimEntity", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ClaimId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ClaimId");

                    b.HasIndex("ClaimId");

                    b.ToTable("UserClaimEntity");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            ClaimId = 1,
                            Id = 1
                        },
                        new
                        {
                            UserId = 2,
                            ClaimId = 2,
                            Id = 2
                        },
                        new
                        {
                            UserId = 3,
                            ClaimId = 3,
                            Id = 3
                        });
                });

            modelBuilder.Entity("userApi.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2022, 5, 1, 18, 3, 12, 191, DateTimeKind.Local).AddTicks(3582),
                            Email = "test@test.com",
                            FirstName = "testFirst",
                            LastName = "testLast",
                            PasswordHash = "$2a$11$0ys3d2/35/oiVnmZEoX4eeJgSUUNOcdSumko46KqGMZfxAgtIMtlO",
                            UpdateDate = new DateTime(2022, 5, 1, 18, 3, 12, 191, DateTimeKind.Local).AddTicks(3591)
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2022, 5, 1, 18, 3, 12, 320, DateTimeKind.Local).AddTicks(5710),
                            Email = "editor@test.com",
                            FirstName = "testFirst",
                            LastName = "testLast",
                            PasswordHash = "$2a$11$BsDWuPOEEMva.zIUL2u4Ve6XeiQ3aS4DlXS2TLfeJ.2zmUiSq5.qm",
                            UpdateDate = new DateTime(2022, 5, 1, 18, 3, 12, 320, DateTimeKind.Local).AddTicks(5725)
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2022, 5, 1, 18, 3, 12, 449, DateTimeKind.Local).AddTicks(9000),
                            Email = "admin@test.com",
                            FirstName = "testFirst",
                            LastName = "testLast",
                            PasswordHash = "$2a$11$g/ArCySEB0zcT/qWnKed4uq8AMirl/bfBHUny46d8ic28TTMK5.6e",
                            UpdateDate = new DateTime(2022, 5, 1, 18, 3, 12, 449, DateTimeKind.Local).AddTicks(9018)
                        });
                });

            modelBuilder.Entity("userApi.Entities.UserClaimEntity", b =>
                {
                    b.HasOne("userApi.Entities.ClaimEntity", "Claim")
                        .WithMany("UserClaim")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("userApi.Entities.UserEntity", "User")
                        .WithMany("UserClaim")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");

                    b.Navigation("User");
                });

            modelBuilder.Entity("userApi.Entities.ClaimEntity", b =>
                {
                    b.Navigation("UserClaim");
                });

            modelBuilder.Entity("userApi.Entities.UserEntity", b =>
                {
                    b.Navigation("UserClaim");
                });
#pragma warning restore 612, 618
        }
    }
}
